name: wcap

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
      deployments: write
        

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Build
        shell: cmd
        run: |
          cd repo && build.cmd
          mkdir wcap
          move wcap.exe .\wcap\

      #- name: Checkout wiki
        #uses: actions/checkout@v3
        #if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        #with:
          #repository: ${{github.repository}}.wiki
          #path: wiki

      - name: Sign binary
        uses: DanaBear/code-sign-action@v4
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.PASSWORD }}'
          folder: 'repo\wcap'
          recursive: false

      - name: Upload binary
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        shell: cmd
        run: |
          #copy repo\wcap.exe wiki
          cd repo\wcap
          7z a wcap.zip wcap.exe
          gh release create v1.0.0 .\wcap.zip --notes "just a mirror-fork" 
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

# cd wiki
# git config --local user.email "action@github.com"
# git config --local user.name "GitHub Action"
# git commit --all --amend --no-edit
# git push --force-with-lease
